version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: 'web'
    volumes:
        - ./src:/var/www/laravel-vue
        - ./etc/config:/var/configs

    ports:
        - "80:80"

    command: /bin/sh -c "cp /var/configs/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always

  laravel:
    image: php:7.4-fpm
    container_name: 'php'
    volumes:
      - ./src:/var/www/laravel-vue
    ports:
      - "9000:9000"
    restart: always

  mysql:
   image: mysql:5.7
   container_name: 'mysql'
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=root

   restart: always





